fix siteget and drupal 8 to be more friendly with local development

diff --git a/scripts/siteget b/scripts/siteget
--- a/scripts/siteget
+++ b/scripts/siteget
@@ -80,28 +80,44 @@ if [ $DRUPALV = "8" ]
 then
     DB=${SITE//-/_}
     settings_file=~/Sites/${SITE}/sites/default/settings.php;
-    echo "Setting up database credentials... This might take a bit...";
-    drush si --db-url=mysql://root:root@localhost/$DB -y > /dev/null 2>&1
-    chmod 775 ~/Sites/$SITE/sites/default
-    if grep -e "\!isset(\$_ENV\['PANTHEON_ENVIRONMENT'\])" ~/Sites/${SITE}/sites/default/settings.php > /dev/null 2>&1; then
-        echo "Pantheon environment conditionals already added!";
-    else
-            chmod 775 ~/Sites/${SITE}/sites/default/settings.php
-            echo "Injecting Pantheon Environment Credentials...";
-            pantheonEnvInject $settings_file
-            echo "Finished Injecting Credentials..."
-            if grep -e "\!isset(\$_ENV\['PANTHEON_ENVIRONMENT'\])" ~/Sites/${SITE}/sites/default/settings.php > /dev/null 2>&1; then
-                echo "Pantheon environment conditionals added successfully!";
-            else
-                echo "There was an error adding the pantheon environment conditionals";
-            fi
+    default_settings_file=~/Sites/${SITE}/sites/default/default.settings.php;
+    settings_file_tmp=~/Sites/${SITE}/sites/default/settings.php-tmp;
+    local_settings=~/Sites/${SITE}/sites/default/settings.local.php;
+    local_settings_template=~/Sites/${SITE}/sites/example.settings.local.php;
+    install_log=~/Sites/${SITE}/install.log;
+    if [ ! -f $local_settings ]; then
+        chmod 775 ~/Sites/$SITE/sites/default
+        echo "${SITE}/sites/default/settings.local.php not found. Setting up local settings file... This might take a bit...";
+        mv $settings_file $settings_file_tmp;
+        drush si --db-url=mysql://root:root@localhost/$DB -y > $install_log 2>&1 & spinner $! || true
+        if [ -f $settings_file ]; then
+            rm $install_log;
+            chmod 775 ~/Sites/$SITE/sites/default
+            chmod 777 $settings_file;
+            cp -f $local_settings_template $local_settings;
+            echo "" >> $local_settings;
+            echo "" >> $local_settings;
+            echo "/**=====================================" >> $local_settings;
+            echo "*            local install" >> $local_settings;
+            echo "*=====================================**/" >> $local_settings;
+            echo "" >> $local_settings;
+            echo "" >> $local_settings;
+            diff "${default_settings_file}" "${settings_file}" | grep ">" | sed 's/^>//g' | sed 's/^\( *\)\(.\)/\1\1\2/g' >> "${local_settings}";
+            rm -f $settings_file;
+            mv -f $settings_file_tmp $settings_file;
+        else
+            echo "Something went wrong...";
+            cat $install_log;
+            exit 1;
+        fi
     fi
+    chmod 775 ~/Sites/$SITE/sites/default
 else
     if [ ! -f sites/default/settings.php ]
     then
         DB=${SITE//-/_}
         echo "No settings.php. creating..."
-        drush si --db-url=mysql://root:root@localhost/$DB -y > /dev/null 2>&1
+        drush si --db-url=mysql://root:root@localhost/$DB -y > /dev/null 2>&1 & spinner $! || true
     fi;
 fi;
 terminus-ssp $SITE $ENV &&
